[package]
name = "wheretests"
version = "0.1.0"
edition = "2021"
license = "0BSD"

[dependencies]
memmap2 = "0.9.4"
# nextest-runner = "0.55.0"
object = "0.35.0"
serde = "1.0.202"
serde_derive = "1.0.202"
serde_json = "1.0.117"
symbolic-debuginfo = "12.8.0"
symbolic-demangle = "12.8.0"
